# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebClient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitors',
            name='monitor_domain',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
