# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebClient', '0002_monitors_monitor_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField()),
                ('metric', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('max_value', models.IntegerField()),
                ('complex_mes', models.BooleanField()),
                ('values', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('number', models.IntegerField()),
                ('total_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('measurements', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='monitors',
            name='monitor_password',
            field=models.CharField(default='password', max_length=200),
        ),
    ]
